- 1.0/TeamPage.html
The files on github page is case-sensitive
> Fixed the Logo on TeamPage.html

- css/main.css
Issue #35 
added some padding-top to Event
> Added: padding to Event

- css/main.css
- index.html
Fixed the hover effect on icons from _footer-special_
> fixed hover effect

- index.html
> Added: SOCIAL MEDIA links

- css/main.css
This pr fixes #68 
Now it is visible in all background and also matches with the theme
> fix arrow to make it visible

- css/main.css
- index.html
Foxed the uneven button layout
> Fixed button layout

- css/main.css
Added: Social media icon-related changes like an alignment of icons color of icons are matching with the theme now.
> Social media icons are now visible properly.

- css/main.css
- index.html
It is looking better.....could you please review it and accept this PR under Hacktoberfest tag. This is my first PR/ first contribution to an opensource.
> fixed the home-screen social icons and applied hover effect(red) on them

- css/main.css
- index.html
Updated telegram button and Teacm section ui new look added
> UI UPDATES

- css/main.css
- css/media-queries.css
Added grid properties to make the event section look good and responsive .
Here are some screenshorts
before
after 
if its ok pls merg as soon as possible 
i got a merg conflict in a pull request 😢 thats quite demotivating
> Added grid to make events responsive

- index.html
I found a bug in my code, I wrote Twitter instead of Linkedin by mistake.
This is an update for that.
> Update social media icon

- index.html
The icon was not visible due to incorrect code, now it's updated with the new one.
<i class="fa fa-quote-left quote"></i>
> Update testimonial quotes

- index.html
Icons are changed and replaced with the new one which is relevant to the heading.
Under **AIM** section.
> Font Awesome icons improvisation

- css/testimonial.css
- js/testimonial.js
Please review:
Testimonial section is not responsive and i want to sliding effect #107
>  Testimonial section made responsive and sliding effect added

- css/main.css
- index.html
1. added new button class in index.html ,for whatsapp,telegram,discord buttons.
2. added custom styling in the main.css file
3. added hover animation in main.css file
Here is the working video of the changes I made. 
https://drive.google.com/file/d/1uQ5Wx-qWsNdBbX0tcFSJ934g3f50Ht08/view?usp=sharing
> Added custom styling and hover effect to main buttons

- css/main.css
> Added Navbar Hovers

- css/main.css
- css/media-queries.css
- index.html
- js/custom.js
Changed Partners section 
https://user-images.githubusercontent.com/59968161/136230100-6c8fc2f5-03f8-451a-8d0f-4d7aa86cf468.mp4
> Changes made to landing page to make UI better

- index.html
Add emailjs code to submit contact form without backend.
**Update your EmailJS credentials here.**
> EmailJS Integrated Contact Form

- intern.html
> Fixed the #256 issue

- about.html
- blog.html
- intern.html
Connected favicon on various pages:
- About
- Blog
- Internship
#263
> Connect favicon on website pages

- css/main.css
fixes #269 
Added underline transition of 800ms while hovering over the navigation menu and enhanced the font size of text while hovering to 13.75p
https://user-images.githubusercontent.com/87245981/157831644-36e4843b-906e-49b8-a607-0eb5a38b54b4.mp4
x
> Modified transition while hovering

- .github/PULL_REQUEST_TEMPLATE.md
Closes #236 
Added PR template
> docs: Added PR Template
